gotcha-ai:
  deep-vision:
    base-path: "/home/app/resources/python/deep-vision"
  sqs:
    detection-request-queue:
      queue-name: gotcha-detection-request-queue-dev
      queue-url: "https://sqs.us-east-1.amazonaws.com/497458231604/gotcha-detection-request-queue-dev"
  dynamodb:
    table-name: 'gotcha-object-detection-dev'
    auto-create: false

micronaut:
  object-storage:
    aws:
      detection-input:
        bucket: gotcha-detection-input-dev
      detection-output:
        bucket: gotcha-detection-output-dev

logger:
  levels:
    ROOT: INFO
    com.gotcha.ai.worker: INFO
    com.gotcha.ai.worker.listener: INFO
    com.gotcha.ai.worker.config.health: INFO