micronaut:
  application:
    name: gotchaAiWorker
  jms:
    sqs:
      enabled: false

gotcha-ai:
  deep-vision:
    detect-script-location: "./python/deep-vision/detect.py"
  sqs:
    detection-request-queue:
      api-call-attempt-timeout: 30000
      api-call-timeout: 120000

logger:
  levels:
    ROOT: INFO

endpoints:
  health:
    enabled: true
    sensitive: Boolean
    details-visible: ANONYMOUS
