
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotcha-ai-worker
spec:
  selector:
    matchLabels:
      app: gotcha-ai-worker
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: gotcha-ai-worker
    spec:
      containers:
        - name: gotcha-ai-worker
          image: liang121900/gotcha-ai-worker:0.0.5
          volumeMounts:
            - name: aws-credential-mount
              mountPath: /root/.aws
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: dev
          livenessProbe: #health check
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 4
            terminationGracePeriodSeconds: 60           
      volumes:
        - name: aws-credential-mount
          hostPath:
            path: /run/desktop/mnt/host/d/gotcha-ai-run-dev/.aws/gotcha-app # your .aws path
            type: Directory
---        